# Autogenerated wrapper script for muparser_jll for aarch64-unknown-freebsd
export libmuparser

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("muparser")
JLLWrappers.@declare_library_product(libmuparser, "libmuparser.so.2")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libmuparser,
        "lib/libmuparser.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
