# Autogenerated wrapper script for muparser_jll for x86_64-apple-darwin
export libmuparser

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("muparser")
JLLWrappers.@declare_library_product(libmuparser, "@rpath/libmuparser.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libmuparser,
        "lib/libmuparser.2.3.5.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
