# Autogenerated wrapper script for muparser_jll for x86_64-w64-mingw32-cxx03
export libmuparser

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("muparser")
JLLWrappers.@declare_library_product(libmuparser, "libmuparser.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmuparser,
        "bin\\libmuparser.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
